export const KOFENOT_PRODUCT = {
  name: "KOFENOT™",
  tagline: "Pocket-sized laptop wedge",
  retail_price: 15,
  bundle_price: 25,
  bundle_qty: 2,
  wholesale_min: 30,
  dimensions: '2.0 × 1.6"',
  material: "ABS",
  weight: "1 oz",
  made_in: "California",
  ships_from: "Los Gatos, CA",
  ship_time: "24–48 hours",
  features: [
    "Protects laptops from coffee spills",
    "Improves posture",
    "Works as phone/tablet stand",
    "Folds flat — pocket-sized",
    "No magnets, clips, or adhesive",
    "Mechanical snap — uses rear hinge gap",
    "SGS tested, RoHS compliant",
    "Patent pending",
    "Branding area for custom logo",
  ],
  certifications: ["SGS tested", "RoHS compliant", "Patent pending"],
  compatible: "Almost every laptop with rear hinge gap",
} as const;

export const TARGET_INDUSTRIES = [
  "Coffee Roaster",
  "Coffee Shop",
  "Tech",
  "Corporate HR",
  "Corporate Marketing",
  "Coworking",
  "Museum",
  "University",
  "Library",
  "Airport Retail",
  "Events",
  "Trade Show",
  "Promo Agency",
  "Retail",
  "Corporate Gifts",
] as const;

export const BUYER_ROLES = [
  "Marketing Manager",
  "Office Manager",
  "HR Director",
  "Procurement",
  "Operations",
  "Owner",
  "Retail Buyer",
  "Events Manager",
  "Community Manager",
] as const;
