/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as OsRouteImport } from './routes/os'
import { Route as PressRouteImport } from './routes/press'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RetailKitRouteImport } from './routes/retail-kit'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as StoryRouteImport } from './routes/story'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as OsIndexRouteImport } from './routes/os/index'
import { Route as OsAnalyticsRouteImport } from './routes/os/analytics'
import { Route as OsCloserRouteImport } from './routes/os/closer'
import { Route as OsCmoRouteImport } from './routes/os/cmo'
import { Route as OsPipelineRouteImport } from './routes/os/pipeline'
import { Route as OsScoutRouteImport } from './routes/os/scout'
import { Route as OsCompaniesIndexRouteImport } from './routes/os/companies/index'
import { Route as OsCompaniesCompanyIdRouteImport } from './routes/os/companies/$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailKitRoute = RetailKitRouteImport.update({
  id: '/retail-kit',
  path: '/retail-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsRoute,
} as any)
const OsAnalyticsRoute = OsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OsRoute,
} as any)
const OsCloserRoute = OsCloserRouteImport.update({
  id: '/closer',
  path: '/closer',
  getParentRoute: () => OsRoute,
} as any)
const OsCmoRoute = OsCmoRouteImport.update({
  id: '/cmo',
  path: '/cmo',
  getParentRoute: () => OsRoute,
} as any)
const OsPipelineRoute = OsPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => OsRoute,
} as any)
const OsScoutRoute = OsScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => OsRoute,
} as any)
const OsCompaniesIndexRoute = OsCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => OsRoute,
} as any)
const OsCompaniesCompanyIdRoute = OsCompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => OsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/downloads': typeof DownloadsRoute
  '/os': typeof OsRouteWithChildren
  '/press': typeof PressRoute
  '/referrals': typeof ReferralsRoute
  '/retail-kit': typeof RetailKitRoute
  '/spec': typeof SpecRoute
  '/story': typeof StoryRoute
  '/wholesale': typeof WholesaleRoute
  '/os/analytics': typeof OsAnalyticsRoute
  '/os/closer': typeof OsCloserRoute
  '/os/cmo': typeof OsCmoRoute
  '/os/pipeline': typeof OsPipelineRoute
  '/os/scout': typeof OsScoutRoute
  '/os/': typeof OsIndexRoute
  '/os/companies/$companyId': typeof OsCompaniesCompanyIdRoute
  '/os/companies/': typeof OsCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/downloads': typeof DownloadsRoute
  '/press': typeof PressRoute
  '/referrals': typeof ReferralsRoute
  '/retail-kit': typeof RetailKitRoute
  '/spec': typeof SpecRoute
  '/story': typeof StoryRoute
  '/wholesale': typeof WholesaleRoute
  '/os/analytics': typeof OsAnalyticsRoute
  '/os/closer': typeof OsCloserRoute
  '/os/cmo': typeof OsCmoRoute
  '/os/pipeline': typeof OsPipelineRoute
  '/os/scout': typeof OsScoutRoute
  '/os': typeof OsIndexRoute
  '/os/companies/$companyId': typeof OsCompaniesCompanyIdRoute
  '/os/companies': typeof OsCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/downloads': typeof DownloadsRoute
  '/os': typeof OsRouteWithChildren
  '/press': typeof PressRoute
  '/referrals': typeof ReferralsRoute
  '/retail-kit': typeof RetailKitRoute
  '/spec': typeof SpecRoute
  '/story': typeof StoryRoute
  '/wholesale': typeof WholesaleRoute
  '/os/analytics': typeof OsAnalyticsRoute
  '/os/closer': typeof OsCloserRoute
  '/os/cmo': typeof OsCmoRoute
  '/os/pipeline': typeof OsPipelineRoute
  '/os/scout': typeof OsScoutRoute
  '/os/': typeof OsIndexRoute
  '/os/companies/$companyId': typeof OsCompaniesCompanyIdRoute
  '/os/companies/': typeof OsCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom'
    | '/downloads'
    | '/os'
    | '/press'
    | '/referrals'
    | '/retail-kit'
    | '/spec'
    | '/story'
    | '/wholesale'
    | '/os/analytics'
    | '/os/closer'
    | '/os/cmo'
    | '/os/pipeline'
    | '/os/scout'
    | '/os/'
    | '/os/companies/$companyId'
    | '/os/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom'
    | '/downloads'
    | '/press'
    | '/referrals'
    | '/retail-kit'
    | '/spec'
    | '/story'
    | '/wholesale'
    | '/os/analytics'
    | '/os/closer'
    | '/os/cmo'
    | '/os/pipeline'
    | '/os/scout'
    | '/os'
    | '/os/companies/$companyId'
    | '/os/companies'
  id:
    | '__root__'
    | '/'
    | '/custom'
    | '/downloads'
    | '/os'
    | '/press'
    | '/referrals'
    | '/retail-kit'
    | '/spec'
    | '/story'
    | '/wholesale'
    | '/os/analytics'
    | '/os/closer'
    | '/os/cmo'
    | '/os/pipeline'
    | '/os/scout'
    | '/os/'
    | '/os/companies/$companyId'
    | '/os/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomRoute: typeof CustomRoute
  DownloadsRoute: typeof DownloadsRoute
  OsRoute: typeof OsRouteWithChildren
  PressRoute: typeof PressRoute
  ReferralsRoute: typeof ReferralsRoute
  RetailKitRoute: typeof RetailKitRoute
  SpecRoute: typeof SpecRoute
  StoryRoute: typeof StoryRoute
  WholesaleRoute: typeof WholesaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail-kit': {
      id: '/retail-kit'
      path: '/retail-kit'
      fullPath: '/retail-kit'
      preLoaderRoute: typeof RetailKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/': {
      id: '/os/'
      path: '/'
      fullPath: '/os/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/analytics': {
      id: '/os/analytics'
      path: '/analytics'
      fullPath: '/os/analytics'
      preLoaderRoute: typeof OsAnalyticsRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/closer': {
      id: '/os/closer'
      path: '/closer'
      fullPath: '/os/closer'
      preLoaderRoute: typeof OsCloserRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/cmo': {
      id: '/os/cmo'
      path: '/cmo'
      fullPath: '/os/cmo'
      preLoaderRoute: typeof OsCmoRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/pipeline': {
      id: '/os/pipeline'
      path: '/pipeline'
      fullPath: '/os/pipeline'
      preLoaderRoute: typeof OsPipelineRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/scout': {
      id: '/os/scout'
      path: '/scout'
      fullPath: '/os/scout'
      preLoaderRoute: typeof OsScoutRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/companies/': {
      id: '/os/companies/'
      path: '/companies'
      fullPath: '/os/companies/'
      preLoaderRoute: typeof OsCompaniesIndexRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/companies/$companyId': {
      id: '/os/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/os/companies/$companyId'
      preLoaderRoute: typeof OsCompaniesCompanyIdRouteImport
      parentRoute: typeof OsRoute
    }
  }
}

interface OsRouteChildren {
  OsAnalyticsRoute: typeof OsAnalyticsRoute
  OsCloserRoute: typeof OsCloserRoute
  OsCmoRoute: typeof OsCmoRoute
  OsPipelineRoute: typeof OsPipelineRoute
  OsScoutRoute: typeof OsScoutRoute
  OsIndexRoute: typeof OsIndexRoute
  OsCompaniesCompanyIdRoute: typeof OsCompaniesCompanyIdRoute
  OsCompaniesIndexRoute: typeof OsCompaniesIndexRoute
}

const OsRouteChildren: OsRouteChildren = {
  OsAnalyticsRoute: OsAnalyticsRoute,
  OsCloserRoute: OsCloserRoute,
  OsCmoRoute: OsCmoRoute,
  OsPipelineRoute: OsPipelineRoute,
  OsScoutRoute: OsScoutRoute,
  OsIndexRoute: OsIndexRoute,
  OsCompaniesCompanyIdRoute: OsCompaniesCompanyIdRoute,
  OsCompaniesIndexRoute: OsCompaniesIndexRoute,
}

const OsRouteWithChildren = OsRoute._addFileChildren(OsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomRoute: CustomRoute,
  DownloadsRoute: DownloadsRoute,
  OsRoute: OsRouteWithChildren,
  PressRoute: PressRoute,
  ReferralsRoute: ReferralsRoute,
  RetailKitRoute: RetailKitRoute,
  SpecRoute: SpecRoute,
  StoryRoute: StoryRoute,
  WholesaleRoute: WholesaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
