import type { Company, Contact, ContentItem, Task } from "../types";

export const DEMO_COMPANIES: Company[] = [
  {
    id: "demo-1",
    name: "Verve Coffee Roasters",
    website: "https://vervecoffee.com",
    industry: "Coffee Roaster",
    employee_count: "200-500",
    location: "Santa Cruz, CA",
    linkedin_url: null,
    buying_reason: "Retail gift shop + employee swag",
    pain_points: ["coffee spills near laptops", "brand visibility in cafes"],
    stage: "qualified",
    probability: 45,
    potential_order_size: 500,
    expected_revenue: 3750,
    next_action: "Send personalized outreach to HR lead",
    last_activity_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    tags: ["coffee", "retail", "hot"],
    research_summary: null,
    ai_entry_point: "Employee onboarding kits for remote baristas",
    is_partner: false,
    is_repeat_customer: false,
    lost_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    name: "SFMOMA",
    website: "https://sfmoma.org",
    industry: "Museum",
    employee_count: "200-500",
    location: "San Francisco, CA",
    linkedin_url: null,
    buying_reason: "Museum store retail + member gifts",
    pain_points: ["unique gift shop items", "local California products"],
    stage: "reply_received",
    probability: 60,
    potential_order_size: 300,
    expected_revenue: 2250,
    next_action: "Schedule call with retail buyer",
    last_activity_at: new Date(Date.now() - 86400000).toISOString(),
    tags: ["museum", "retail", "hot"],
    research_summary: null,
    ai_entry_point: "Museum store retail — Made in California, pocket-sized, unique",
    is_partner: false,
    is_repeat_customer: false,
    lost_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    name: "HubSpot",
    website: "https://hubspot.com",
    industry: "Tech",
    employee_count: "5000+",
    location: "Cambridge, MA",
    linkedin_url: null,
    buying_reason: "Conference swag + sales kits",
    pain_points: ["swag fatigue at trade shows"],
    stage: "meeting_scheduled",
    probability: 70,
    potential_order_size: 1500,
    expected_revenue: 11250,
    next_action: "Prepare meeting brief",
    last_activity_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    tags: ["tech", "events", "priority"],
    research_summary: null,
    ai_entry_point: "INBOUND conference booth giveaway",
    is_partner: false,
    is_repeat_customer: false,
    lost_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    name: "Peet's Coffee",
    website: "https://peets.com",
    industry: "Coffee Roaster",
    employee_count: "1000+",
    location: "Emeryville, CA",
    linkedin_url: null,
    buying_reason: "Corporate gifting + cafe retail",
    pain_points: ["brand extension beyond coffee"],
    stage: "sample_shipped",
    probability: 55,
    potential_order_size: 800,
    expected_revenue: 6000,
    next_action: "Sample follow-up — check if received",
    last_activity_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    tags: ["coffee", "corporate"],
    research_summary: null,
    ai_entry_point: "Co-branded retail in cafes + corporate holiday gifting",
    is_partner: false,
    is_repeat_customer: false,
    lost_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    name: "Anthropologie",
    website: "https://anthropologie.com",
    industry: "Retail",
    employee_count: "5000+",
    location: "Philadelphia, PA",
    linkedin_url: null,
    buying_reason: "Gift shop retail",
    pain_points: ["unique desk accessories"],
    stage: "won",
    probability: 100,
    potential_order_size: 2000,
    expected_revenue: 15000,
    next_action: "Send reorder reminder in 90 days",
    last_activity_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    tags: ["retail", "won"],
    research_summary: null,
    ai_entry_point: "Gift shop retail placement",
    is_partner: false,
    is_repeat_customer: true,
    lost_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: "demo-t1",
    company_id: "demo-2",
    contact_id: null,
    title: "Follow up with SFMOMA retail buyer",
    description: "Reply received — schedule call",
    due_at: new Date(Date.now() + 86400000).toISOString(),
    priority: "urgent",
    status: "pending",
    task_type: "follow_up",
    ai_generated: true,
    created_at: new Date().toISOString(),
    completed_at: null,
    company: { id: "demo-2", name: "SFMOMA", stage: "reply_received" },
  },
  {
    id: "demo-t2",
    company_id: "demo-3",
    contact_id: null,
    title: "Prepare HubSpot meeting brief",
    description: "Meeting tomorrow",
    due_at: new Date().toISOString(),
    priority: "urgent",
    status: "pending",
    task_type: "meeting_prep",
    ai_generated: true,
    created_at: new Date().toISOString(),
    completed_at: null,
    company: { id: "demo-3", name: "HubSpot", stage: "meeting_scheduled" },
  },
  {
    id: "demo-t3",
    company_id: "demo-4",
    contact_id: null,
    title: "Sample follow-up — Peet's Coffee",
    description: "Sample shipped 7 days ago",
    due_at: new Date(Date.now() - 86400000).toISOString(),
    priority: "high",
    status: "pending",
    task_type: "follow_up",
    ai_generated: true,
    created_at: new Date().toISOString(),
    completed_at: null,
    company: { id: "demo-4", name: "Peet's Coffee", stage: "sample_shipped" },
  },
];

export const DEMO_CONTACTS: Record<string, Contact[]> = {
  "demo-1": [
    {
      id: "demo-c1",
      company_id: "demo-1",
      name: "Sarah Chen",
      email: "schen@vervecoffee.com",
      phone: null,
      role: "HR Director",
      linkedin_url: "https://linkedin.com/in/sarahchen",
      is_decision_maker: true,
      notes: null,
      created_at: new Date().toISOString(),
    },
  ],
  "demo-2": [
    {
      id: "demo-c2",
      company_id: "demo-2",
      name: "Lisa Park",
      email: "lpark@sfmoma.org",
      phone: null,
      role: "Retail Buyer",
      linkedin_url: null,
      is_decision_maker: true,
      notes: null,
      created_at: new Date().toISOString(),
    },
  ],
  "demo-3": [
    {
      id: "demo-c3",
      company_id: "demo-3",
      name: "James Okonkwo",
      email: "jokonkwo@hubspot.com",
      phone: null,
      role: "Events Marketing Manager",
      linkedin_url: null,
      is_decision_maker: true,
      notes: null,
      created_at: new Date().toISOString(),
    },
  ],
};

export const DEMO_CONTENT: ContentItem[] = [
  {
    id: "demo-content-1",
    title: "Why coffee shops love KOFENOT",
    type: "linkedin",
    body: "Your customers bring laptops. Coffee spills happen. KOFENOT sits in the hinge gap — pocket-sized, no magnets, no adhesive.",
    status: "draft",
    scheduled_for: new Date(Date.now() + 86400000).toISOString(),
    metadata: {},
    ai_generated: true,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_OBJECTIONS = [
  {
    id: "demo-o1",
    objection: "Too expensive",
    category: "price",
    best_response:
      "At $15 retail with 2-for-$25, KOFENOT costs less per impression than most swag — and people actually keep it on their desk daily.",
    usage_count: 0,
    success_rate: null,
  },
  {
    id: "demo-o2",
    objection: "Need samples",
    category: "samples",
    best_response:
      "I ship samples within 24–48 hours from our Los Gatos inventory. Send me your address and I'll include spec sheets.",
    usage_count: 0,
    success_rate: null,
  },
];

export function isDemoMode(): boolean {
  return !process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY;
}
